POST https://api.github.com/repos/agorapulse/agorapulse-oss/dispatches
Accept:  application/vnd.github.everest-preview+json
Content-Type: application/json
Authorization: Bearer {{personal_token}}

{
    "event_type": "ap-new-version-released-event",
    "client_payload": {
        "group": "com.agorapulse",
        "module": "grails-ap-bootstrap",
        "version": "9.0.8.1",
        "property": "agorapulse.plugins.bootstrap.version",
        "github": {
            "token": "***",
            "job": "ping",
            "ref": "refs/tags/9.0.8.1",
            "sha": "0e0af528e8ce274aa7936d3f3d32852a95c740e3",
            "repository": "agorapulse/micronaut-worker",
            "repository_owner": "agorapulse",
            "repositoryUrl": "git://github.com/agorapulse/micronaut-worker.git",
            "run_id": "315157217",
            "run_number": "6",
            "retention_days": "90",
            "actor": "musketyr",
            "workflow": "Publish Libraries",
            "head_ref": "",
            "base_ref": "",
            "event_name": "release",
            "event": {
                "action": "published",
                "organization": {
                    "avatar_url": "https://avatars1.githubusercontent.com/u/3104895?v=4",
                    "description": "",
                    "events_url": "https://api.github.com/orgs/agorapulse/events",
                    "hooks_url": "https://api.github.com/orgs/agorapulse/hooks",
                    "id": 3104895,
                    "issues_url": "https://api.github.com/orgs/agorapulse/issues",
                    "login": "agorapulse",
                    "members_url": "https://api.github.com/orgs/agorapulse/members{/member}",
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjMxMDQ4OTU=",
                    "public_members_url": "https://api.github.com/orgs/agorapulse/public_members{/member}",
                    "repos_url": "https://api.github.com/orgs/agorapulse/repos",
                    "url": "https://api.github.com/orgs/agorapulse"
                },
                "release": {
                    "assets": [],
                    "assets_url": "https://api.github.com/repos/agorapulse/micronaut-worker/releases/32744071/assets",
                    "author": {
                        "avatar_url": "https://avatars1.githubusercontent.com/u/660405?v=4",
                        "events_url": "https://api.github.com/users/musketyr/events{/privacy}",
                        "followers_url": "https://api.github.com/users/musketyr/followers",
                        "following_url": "https://api.github.com/users/musketyr/following{/other_user}",
                        "gists_url": "https://api.github.com/users/musketyr/gists{/gist_id}",
                        "gravatar_id": "",
                        "html_url": "https://github.com/musketyr",
                        "id": 660405,
                        "login": "musketyr",
                        "node_id": "MDQ6VXNlcjY2MDQwNQ==",
                        "organizations_url": "https://api.github.com/users/musketyr/orgs",
                        "received_events_url": "https://api.github.com/users/musketyr/received_events",
                        "repos_url": "https://api.github.com/users/musketyr/repos",
                        "site_admin": false,
                        "starred_url": "https://api.github.com/users/musketyr/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/musketyr/subscriptions",
                        "type": "User",
                        "url": "https://api.github.com/users/musketyr"
                    },
                    "body": "* synchronized with the latest platform code\r\n* split the NewRelic related code into a small library\r\n\r\n(re-release)",
                    "created_at": "2020-10-19T09:14:11Z",
                    "draft": false,
                    "html_url": "https://github.com/agorapulse/micronaut-worker/releases/tag/9.0.8.1",
                    "id": 32744071,
                    "name": "9.0.8.1",
                    "node_id": "MDc6UmVsZWFzZTMyNzQ0MDcx",
                    "prerelease": false,
                    "published_at": "2020-10-19T09:30:13Z",
                    "tag_name": "9.0.8.1",
                    "tarball_url": "https://api.github.com/repos/agorapulse/micronaut-worker/tarball/9.0.8.1",
                    "target_commitish": "master",
                    "upload_url": "https://uploads.github.com/repos/agorapulse/micronaut-worker/releases/32744071/assets{?name,label}",
                    "url": "https://api.github.com/repos/agorapulse/micronaut-worker/releases/32744071",
                    "zipball_url": "https://api.github.com/repos/agorapulse/micronaut-worker/zipball/9.0.8.1"
                },
                "repository": {
                    "archive_url": "https://api.github.com/repos/agorapulse/micronaut-worker/{archive_format}{/ref}",
                    "archived": false,
                    "assignees_url": "https://api.github.com/repos/agorapulse/micronaut-worker/assignees{/user}",
                    "blobs_url": "https://api.github.com/repos/agorapulse/micronaut-worker/git/blobs{/sha}",
                    "branches_url": "https://api.github.com/repos/agorapulse/micronaut-worker/branches{/branch}",
                    "clone_url": "https://github.com/agorapulse/micronaut-worker.git",
                    "collaborators_url": "https://api.github.com/repos/agorapulse/micronaut-worker/collaborators{/collaborator}",
                    "comments_url": "https://api.github.com/repos/agorapulse/micronaut-worker/comments{/number}",
                    "commits_url": "https://api.github.com/repos/agorapulse/micronaut-worker/commits{/sha}",
                    "compare_url": "https://api.github.com/repos/agorapulse/micronaut-worker/compare/{base}...{head}",
                    "contents_url": "https://api.github.com/repos/agorapulse/micronaut-worker/contents/{+path}",
                    "contributors_url": "https://api.github.com/repos/agorapulse/micronaut-worker/contributors",
                    "created_at": "2019-07-08T05:24:20Z",
                    "default_branch": "master",
                    "deployments_url": "https://api.github.com/repos/agorapulse/micronaut-worker/deployments",
                    "description": "Agrorapulse Bootstrap Plugin",
                    "disabled": false,
                    "downloads_url": "https://api.github.com/repos/agorapulse/micronaut-worker/downloads",
                    "events_url": "https://api.github.com/repos/agorapulse/micronaut-worker/events",
                    "fork": false,
                    "forks": 0,
                    "forks_count": 0,
                    "forks_url": "https://api.github.com/repos/agorapulse/micronaut-worker/forks",
                    "full_name": "agorapulse/micronaut-worker",
                    "git_commits_url": "https://api.github.com/repos/agorapulse/micronaut-worker/git/commits{/sha}",
                    "git_refs_url": "https://api.github.com/repos/agorapulse/micronaut-worker/git/refs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/agorapulse/micronaut-worker/git/tags{/sha}",
                    "git_url": "git://github.com/agorapulse/micronaut-worker.git",
                    "has_downloads": true,
                    "has_issues": true,
                    "has_pages": false,
                    "has_projects": true,
                    "has_wiki": true,
                    "homepage": "",
                    "hooks_url": "https://api.github.com/repos/agorapulse/micronaut-worker/hooks",
                    "html_url": "https://github.com/agorapulse/micronaut-worker",
                    "id": 195741908,
                    "issue_comment_url": "https://api.github.com/repos/agorapulse/micronaut-worker/issues/comments{/number}",
                    "issue_events_url": "https://api.github.com/repos/agorapulse/micronaut-worker/issues/events{/number}",
                    "issues_url": "https://api.github.com/repos/agorapulse/micronaut-worker/issues{/number}",
                    "keys_url": "https://api.github.com/repos/agorapulse/micronaut-worker/keys{/key_id}",
                    "labels_url": "https://api.github.com/repos/agorapulse/micronaut-worker/labels{/name}",
                    "language": "CSS",
                    "languages_url": "https://api.github.com/repos/agorapulse/micronaut-worker/languages",
                    "license": null,
                    "merges_url": "https://api.github.com/repos/agorapulse/micronaut-worker/merges",
                    "milestones_url": "https://api.github.com/repos/agorapulse/micronaut-worker/milestones{/number}",
                    "mirror_url": null,
                    "name": "grails-ap-bootstrap",
                    "node_id": "MDEwOlJlcG9zaXRvcnkxOTU3NDE5MDg=",
                    "notifications_url": "https://api.github.com/repos/agorapulse/micronaut-worker/notifications{?since,all,participating}",
                    "open_issues": 0,
                    "open_issues_count": 0,
                    "owner": {
                        "avatar_url": "https://avatars1.githubusercontent.com/u/3104895?v=4",
                        "events_url": "https://api.github.com/users/agorapulse/events{/privacy}",
                        "followers_url": "https://api.github.com/users/agorapulse/followers",
                        "following_url": "https://api.github.com/users/agorapulse/following{/other_user}",
                        "gists_url": "https://api.github.com/users/agorapulse/gists{/gist_id}",
                        "gravatar_id": "",
                        "html_url": "https://github.com/agorapulse",
                        "id": 3104895,
                        "login": "agorapulse",
                        "node_id": "MDEyOk9yZ2FuaXphdGlvbjMxMDQ4OTU=",
                        "organizations_url": "https://api.github.com/users/agorapulse/orgs",
                        "received_events_url": "https://api.github.com/users/agorapulse/received_events",
                        "repos_url": "https://api.github.com/users/agorapulse/repos",
                        "site_admin": false,
                        "starred_url": "https://api.github.com/users/agorapulse/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/agorapulse/subscriptions",
                        "type": "Organization",
                        "url": "https://api.github.com/users/agorapulse"
                    },
                    "private": true,
                    "pulls_url": "https://api.github.com/repos/agorapulse/micronaut-worker/pulls{/number}",
                    "pushed_at": "2020-10-19T09:30:13Z",
                    "releases_url": "https://api.github.com/repos/agorapulse/micronaut-worker/releases{/id}",
                    "size": 31154,
                    "ssh_url": "git@github.com:agorapulse/micronaut-worker.git",
                    "stargazers_count": 0,
                    "stargazers_url": "https://api.github.com/repos/agorapulse/micronaut-worker/stargazers",
                    "statuses_url": "https://api.github.com/repos/agorapulse/micronaut-worker/statuses/{sha}",
                    "subscribers_url": "https://api.github.com/repos/agorapulse/micronaut-worker/subscribers",
                    "subscription_url": "https://api.github.com/repos/agorapulse/micronaut-worker/subscription",
                    "svn_url": "https://github.com/agorapulse/micronaut-worker",
                    "tags_url": "https://api.github.com/repos/agorapulse/micronaut-worker/tags",
                    "teams_url": "https://api.github.com/repos/agorapulse/micronaut-worker/teams",
                    "trees_url": "https://api.github.com/repos/agorapulse/micronaut-worker/git/trees{/sha}",
                    "updated_at": "2020-10-19T09:14:18Z",
                    "url": "https://api.github.com/repos/agorapulse/micronaut-worker",
                    "watchers": 0,
                    "watchers_count": 0
                },
                "sender": {
                    "avatar_url": "https://avatars1.githubusercontent.com/u/660405?v=4",
                    "events_url": "https://api.github.com/users/musketyr/events{/privacy}",
                    "followers_url": "https://api.github.com/users/musketyr/followers",
                    "following_url": "https://api.github.com/users/musketyr/following{/other_user}",
                    "gists_url": "https://api.github.com/users/musketyr/gists{/gist_id}",
                    "gravatar_id": "",
                    "html_url": "https://github.com/musketyr",
                    "id": 660405,
                    "login": "musketyr",
                    "node_id": "MDQ6VXNlcjY2MDQwNQ==",
                    "organizations_url": "https://api.github.com/users/musketyr/orgs",
                    "received_events_url": "https://api.github.com/users/musketyr/received_events",
                    "repos_url": "https://api.github.com/users/musketyr/repos",
                    "site_admin": false,
                    "starred_url": "https://api.github.com/users/musketyr/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/musketyr/subscriptions",
                    "type": "User",
                    "url": "https://api.github.com/users/musketyr"
                }
            },
            "server_url": "https://github.com",
            "api_url": "https://api.github.com",
            "graphql_url": "https://api.github.com/graphql",
            "workspace": "/home/runner/work/grails-ap-bootstrap/grails-ap-bootstrap",
            "action": "peter-evansrepository-dispatch",
            "event_path": "/home/runner/work/_temp/_github_workflow/event.json",
            "path": "/home/runner/work/_temp/_runner_file_commands/add_path_f1d336ca-5a5d-4940-9a91-4d63cced23c7",
            "env": "/home/runner/work/_temp/_runner_file_commands/set_env_f1d336ca-5a5d-4940-9a91-4d63cced23c7"
        }
    }
}
